### ISSUE TITLE
Define Thing discovery mechanisms

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/wot#20] opened 2017-03-28 13:29 UTC
Decide whether to specify Web Thing discovery mechanisms in this specification, in an accompanying note or not at all. Examples of discovery mechanisms might include looking up in a directory (e.g. on a gateway or in the cloud), crawling/indexing/searching using a search engine, proximity based broadcasts (e.g. using physical web beacons) and local network based broadcasts (e.g. using CoAP, UPnP or mDNS).

Maybe combine with Integration Patterns note and call it Web of Things Design Patterns.

**Comment by benfrancis** [comment] 2017-03-28 13:30
Related: Does there need to be an API method for a gateway to scan for devices to add, or should that be implementation specific?

**Comment by mrstegeman** [comment] 2018-03-28 16:44
Duplicate of #75

**Closed by mrstegeman** 2018-03-28 16:44 UTC
